### ISSUE TITLE
Feature Request EDL Support

### ISSUE THREAD

**Issue by TheFu** [ozmartian/vidcutter#1]
Please consider adding EDL support as produced by comskip and VideoReDo.
Would be ideal if EDL markers could be manually tweaked, since comskip isn't always right.

TIA

**Comment by ozmartian** [comment]
@TheFu 

I'll take a look at what that all entails and let you know ASAP

**Comment by ozmartian** [comment]
Testing/UAT/QA

**Comment by ozmartian** [comment]
Will be released in next version in a couple of days, maybe sooner.

**Comment by ozmartian** [comment]
But can be checked out from Git master right now if you know your way around this stuff.

**Comment by ozmartian** [comment]
MPlayer EDL files supported as new feature in latest v2.5.0 so you can now save the clip index for a video and reload it for reprocessing etc.

I plan on adding support for ComSkip's EDL files allowing your to import/export between the apps but is pushed out to the next version. ComSkip reports timings by frame number whereas the Qt multimedia package is hell bent on milliseconds. That together with the usual frame drops every few seconds makes it a pain to calculate and track manually so I am exploring easier/reliable ways to achieve this.

**Comment by TheFu** [comment]
Thanks!
Some of my tools also generate EDL files with :hh.mm:SS.ssss timings.  The hh and  '.ssss' are optional.
Basically, my use is to validate and correct cut locations generated by comskip or other tools (videoredo).  mplayer and mpv playback programs support all 3 time-formats.

I will often manually create an EDL file for sports recordings to retain only the best plays. Actually, use a script (perl) to parse the EDL and it generates a "mkvmerge --split parts" command.

Would a few keyboard suggestions be ok?
cntl-s - to save a video.
cntl-p - to save an EDL file.
[ - to set the left cut  (F3 also works - videoredo)
] to set the right cut (F4 also works - videoredo)

Regardless, thanks for your efforts on this!  Might be able to drop my remaining need for a commercial OS with this. THANKS! THANKS!  You may have convinced me to look at python a little more.
