### ISSUE TITLE
LICENSE and README.md are installed in /usr

### ISSUE THREAD

**Issue by luigino** [ozmartian/vidcutter#10]
As per subject, I couldn't find a switch to use with setuptools to correct this.

Since every other path is hardcoded for linux, couldn't the same be done for this?
(e.g. /usr/share/doc/packages/vidcutter)

**Comment by ozmartian** [comment]
Thanks for reporting this. This is a more recent bug that obviously went unnoticed while prepping the new version for release in a day or two. I'll get this fixed immediately. Those files belong in the same folder as the package source files under /usr/lib/python3.6/site_packages/.

I've fixed the code so it no longer occurs in both master and mpv branches. mpv branch is the new release that will be merged back to master and released as v3 in about a day.

Thanks again,
Pete
