### ISSUE TITLE
Fedora installation shouldn't suggest UnitedRPM

### ISSUE THREAD

**Issue by horizonbrave** [ozmartian/vidcutter#108]
I'd rather see the developers suggesting rpmfusion repositories for the missing libraries.
Not sure if you are affiliated with UnitedRPMs but if so this ticket could be handy for you guys to fix your github page written in fully broken/childish english (attacking other people work and with hard to understand sentences). Sorry for harsh words but those pages make the project look dodgy and not reliable (you can find some other similar comments on Interweb). I'd rather see your work appreciated and competitive with others rather than not considered because of some poor PR choices. Thanks a lot :)

**Comment by ozmartian** [comment]
@horizonbrave much appreciated for the heads up.. closing this for obvious reasons (being an Arch-guy myself i know next to nothing re Fedora other than packaging RPMs for you guys :-)

**Comment by kuboosoft** [comment]
@horizonbrave you are a "rpmfusion believer"... Everyone has the freedom to choose what they want ... rpmfusion or unitedrpms, the people choise it... The monopoly ended, accept it. Good luck
