### ISSUE TITLE
AppImage does not run on older systems

### ISSUE THREAD

**Issue by probonopd** [ozmartian/vidcutter#13]
Please don't use xenial ingredients for the AppImage, xenial is too new which means that the resulting AppImage will only run on very new systems. Using precise or trusty ingredients would be much better.

For more background on this, see [here](https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages#creating-portable-appimages).

**Comment by ozmartian** [comment]
@probonopd 

as per my previous msg, latest AppImage is now built on bare bones trusty via liveCD so all should be as per your recommendations. please confirm that this is the case if you have a chance to test it.

many thanks
