### ISSUE TITLE
Cutting a video results in <class 'AttributeError'>: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Dyras** [ozmartian/vidcutter#138]
Greetings. I'm trying to cut this video in VidCutter 5.5.0: https://u.teknik.io/9yavu.zip
From the very beginning up until 24.080.
The video was originally recorded on a Moto G4, then compressed upon upload onto Google Photos and then downloaded onto Windows 10 Pro N where I open the video in VidCutter.

This is what the console tells me:
![2018-02-06_17-27-52](https://user-images.githubusercontent.com/12563436/35873976-996a972c-0b6b-11e8-9fd8-877f4817f37a.png)

Any ideas? 🤔

**Comment by ozmartian** [comment]
@dyras will take a look ... thanks for the quick feedback...

**Comment by ozmartian** [comment]
@Dyras issue has been found and I am in the process of issuing a bugfix release..check back in an hour or so and new versions should be available...

thanks for alerting me to this!

**Comment by Dyras** [comment]
@ozmartian now I'm getting some other message instead and it's still stuck at 60% :(
![image](https://user-images.githubusercontent.com/12563436/35939472-856e6258-0c4c-11e8-8a7d-d6d8c950a5f7.png)
