### ISSUE TITLE
Multi audio streams

### ISSUE THREAD

**Issue by peresz** [ozmartian/vidcutter#14]
I've found problem with cutting videos with multi audio streams. During cutting process only first audio stream is leaving in a result file.

App ver 3.0.0

**Comment by ozmartian** [comment]
@peresz 

thanks for your message.. i've actually not ever tested multiple audio as i dont have the need personally :-) so i would expect this to not work properly but it should be very easy for me to fix and get supported.

did this work on earlier versions and only now stopped working with recently released v3? or are you a new user uing v3 for the first time? knowing this helps me identify where to look to fix ASAP.

thanks!

**Comment by peresz** [comment]
I was not able to test on v2.5 because it didn't work on windows 10 pro x64 (crash during opening file).

**Comment by ozmartian** [comment]
@peresz 

i had some time this afternoon and have added multistream support.  i just need to produce new builds and upload them here. should have a new version for Win x64 uploaded within an hour...

**Comment by ozmartian** [comment]
@peresz 

all done...  grab the win x64 installer from the releases page and it should now keep your multiple audio streams intact... let me know how you go...

**Comment by peresz** [comment]
Hi, i've checked and unfortunately it's not working properly. After saving - program not generate any file and i see message:
![obraz](https://cloud.githubusercontent.com/assets/12275345/23622232/2c3b2698-029e-11e7-9d7a-80c1cb183db9.png)

**Comment by wb63** [comment]
Multi Audi does work to split videos. But it will only concatenate one audio stream, i.e. joining videos does not work with multiple audio.
I am using VidCutter 5.0.5 (64bit) on Linux Mint 18.3
