### ISSUE TITLE
macOS load project file

### ISSUE THREAD

**Issue by jkt628** [ozmartian/vidcutter#180]
the README says

```text
Usage: vidcutter [options] [video] [project]
```
but neither release dmg nor `brew cask` provide vidcutter executable.

nor does this work:

```bash
open -a VidCutter foo.mov foo.vcp
```

**Comment by ferdnyc** [comment]
As far as the executable, I'm not sure, that's a macOS thing. I assume the executable is somewhere inside `VidCutter.app`. 

But as far as usage, the help should really read:

```
Usage: vidcutter [options] [video | project]
```

The video path is stored in the project file, so you don't pass it in when loading a saved project.
