### ISSUE TITLE
Vidcutter 6.0 cannot start

### ISSUE THREAD

**Issue by WebShapedBiz** [ozmartian/vidcutter#184]
Hi.
I've just updated my Vidcutter to 6.0.0~201808021324~ubuntu16.04.1 and it won't start, had no issues with the previous version.

This is the error message:
> Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==6.0.0', 'gui_scripts', 'vidcutter')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 36, in <module>
    from PyQt5.QtGui import (QCloseEvent, QContextMenuEvent, QDragEnterEvent, QDropEvent, QGuiApplication, QMouseEvent,
ImportError: cannot import name 'qt_set_sequence_auto_mnemonic'

OS: ElementaryOS Loki 0.4.1. (Ubuntu 16.04 based)
Uname: Linux ProOne400 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Installed Python versons 2.7.12 and 3.5.2

Cheers.

**Comment by txat** [comment]
Exactly same issue here. Ubuntu 16.04

**Comment by elasti-eduardm** [comment]
The same issue
Linux-mint 18.2

**Comment by revjasper** [comment]
Ubuntu MATE 16.04.5: 
Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==6.0.0', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 36, in <module>
    from PyQt5.QtGui import (QCloseEvent, QContextMenuEvent, QDragEnterEvent, QDropEvent, QGuiApplication, QMouseEvent,
ImportError: cannot import name 'qt_set_sequence_auto_mnemonic'

**Comment by jforce** [comment]
Same

**Comment by sjzaib** [comment]
Exactly the same error on my Ubuntu box

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"

**Comment by srbcheema1** [comment]
Exactly same issue

**Comment by juicechu** [comment]
Exactly same issue Ubuntu 16.04

**Comment by colibris79** [comment]
I am getting the same error. Tried deleting what @zellerede was suggesting but I still get errors (I guess I didn't edit it the right way)
Any suggestions?

**Comment by arezi** [comment]
me too

**Comment by funkybunky** [comment]
> The missing '**qt_set_sequence_auto_mnemonic**' is a MACINTOSH specific QT function, for keyboard shortcuts, according to this [documentation](http://tool.oschina.net/uploads/apidocs/qt/qtglobal.html#qt_set_sequence_auto_mnemonic).
> 
> An easy workaround for this is to simply delete both occurances of '**qt_set_sequence_auto_mnemonic**' in the `__main__.py` file, located at `/usr/lib/python3/dist-packages/vidcutter/__main__.py` (as also written in the errortrace).

I did that, but then another error appears: 
`AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'`

In Result: Vidcutter still doesn't start..

**Comment by vitidev** [comment]
@funkybunky 

`apt install python3-pip`
`pip3 install --upgrade PyOpenGL `

**Comment by funkybunky** [comment]
@vitidev 
Thanks! Haven't tried your solution, though.
I actually solved it in the meantime: It works well when using Flatpak :) 
Before that I was using apt.

**Comment by SPDurkee** [comment]
Same issue here using the apt:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==6.0.0', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 36, in <module>
    from PyQt5.QtGui import (QCloseEvent, QContextMenuEvent, QDragEnterEvent, QDropEvent, QGuiApplication, QMouseEvent,
ImportError: cannot import name 'qt_set_sequence_auto_mnemonic'

**Comment by danrugeles** [comment]
> > The missing '**qt_set_sequence_auto_mnemonic**' is a MACINTOSH specific QT function, for keyboard shortcuts, according to this [documentation](http://tool.oschina.net/uploads/apidocs/qt/qtglobal.html#qt_set_sequence_auto_mnemonic).
> > An easy workaround for this is to simply delete both occurances of '**qt_set_sequence_auto_mnemonic**' in the `__main__.py` file, located at `/usr/lib/python3/dist-packages/vidcutter/__main__.py` (as also written in the errortrace).
> 
> I did that, but then another error appears:
> `AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'`
> 
> In Result: Vidcutter still doesn't start..

I ran into the exact same problem. However, flatpak did not work for me on Ubuntu 16.04, snap didn't work either. 

Thanks to the whole thread, I managed to make vidcutter 6.0.0 work by:
1. Installing vidcutter via apt
2. sudo pip3 install --upgrade PyOpenGL (which upgraded my version from  PyOpenGL-3.0.2 to  PyOpenGL-3.1.0)
3. Commenting out the following lines (at /usr/lib/python3/dist-packages/vidcutter/main.py) as they didn't let vidcutter start:
#from PyQt5.QtGui import (QCloseEvent, QContextMenuEvent, QDragEnterEvent, QDropEvent, QGuiApplication, QMouseEvent,QResizeEvent, QSurfaceFormat, qt_set_sequence_auto_mnemonic)
#qt_set_sequence_auto_mnemonic(False)
#app.setDesktopFileName(vidcutter.__desktopid__)

**Comment by mustafa-kmindz** [comment]
> > > The missing '**qt_set_sequence_auto_mnemonic**' is a MACINTOSH specific QT function, for keyboard shortcuts, according to this [documentation](http://tool.oschina.net/uploads/apidocs/qt/qtglobal.html#qt_set_sequence_auto_mnemonic).
> > > An easy workaround for this is to simply delete both occurances of '**qt_set_sequence_auto_mnemonic**' in the `__main__.py` file, located at `/usr/lib/python3/dist-packages/vidcutter/__main__.py` (as also written in the errortrace).
> > 
> > 
> > I did that, but then another error appears:
> > `AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'`
> > In Result: Vidcutter still doesn't start..
> 
> I ran into the exact same problem. However, flatpak did not work for me on Ubuntu 16.04, snap didn't work either.
> 
> Thanks to the whole thread, I managed to make vidcutter 6.0.0 work by:
> 
> 1. Installing vidcutter via apt
> 2. sudo pip3 install --upgrade PyOpenGL (which upgraded my version from  PyOpenGL-3.0.2 to  PyOpenGL-3.1.0)
> 3. Commenting out the following lines (at /usr/lib/python3/dist-packages/vidcutter/main.py) as they didn't let vidcutter start:
>    #from PyQt5.QtGui import (QCloseEvent, QContextMenuEvent, QDragEnterEvent, QDropEvent, QGuiApplication, QMouseEvent,QResizeEvent, QSurfaceFormat, qt_set_sequence_auto_mnemonic)
>    #qt_set_sequence_auto_mnemonic(False)
>    #app.setDesktopFileName(vidcutter.**desktopid**)

I aslo managed to open vidcutter by doing the said changes in the above comment except I did not comment the below mention line completely, I just removed 'qt_set_sequence_auto_mnemonic' from the arguments and it worked:
> from PyQt5.QtGui import (QCloseEvent, QContextMenuEvent, QDragEnterEvent, QDropEvent, QGuiApplication, QMouseEvent,QResizeEvent, QSurfaceFormat)

**Comment by HLF-Developer** [comment]
> > > The missing '**qt_set_sequence_auto_mnemonic**' is a MACINTOSH specific QT function, for keyboard shortcuts, according to this [documentation](http://tool.oschina.net/uploads/apidocs/qt/qtglobal.html#qt_set_sequence_auto_mnemonic).
> > > An easy workaround for this is to simply delete both occurances of '**qt_set_sequence_auto_mnemonic**' in the `__main__.py` file, located at `/usr/lib/python3/dist-packages/vidcutter/__main__.py` (as also written in the errortrace).
> > 
> > 
> > I did that, but then another error appears:
> > `AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'`
> > In Result: Vidcutter still doesn't start..
> 
> I ran into the exact same problem. However, flatpak did not work for me on Ubuntu 16.04, snap didn't work either.
> 
> Thanks to the whole thread, I managed to make vidcutter 6.0.0 work by:
> 
> 1. Installing vidcutter via apt
> 2. sudo pip3 install --upgrade PyOpenGL (which upgraded my version from  PyOpenGL-3.0.2 to  PyOpenGL-3.1.0)
> 3. Commenting out the following lines (at /usr/lib/python3/dist-packages/vidcutter/main.py) as they didn't let vidcutter start:
>    #from PyQt5.QtGui import (QCloseEvent, QContextMenuEvent, QDragEnterEvent, QDropEvent, QGuiApplication, QMouseEvent,QResizeEvent, QSurfaceFormat, qt_set_sequence_auto_mnemonic)
>    #qt_set_sequence_auto_mnemonic(False)
>    #app.setDesktopFileName(vidcutter.**desktopid**)

I aslo managed to open vidcutter by doing the above said changes except I did not comment the below mentioned line completely, I just removed 'qt_set_sequence_auto_mnemonic' from the arguments and it worked:

> from PyQt5.QtGui import (QCloseEvent, QContextMenuEvent, QDragEnterEvent, QDropEvent, QGuiApplication, QMouseEvent,QResizeEvent, QSurfaceFormat)

**Comment by ozmartian** [comment]
Thanks for the write back and all. qt_set_sequence_auto_mnemonic will be removed in the next version release.



Cheers,

Pete



---- On Mon, 07 Oct 2019 17:01:51 +1100 HLF-Developer <notifications@github.com> wrote ----


The missing 'qt_set_sequence_auto_mnemonic' is a MACINTOSH specific QT function, for keyboard shortcuts, according to this http://tool.oschina.net/uploads/apidocs/qt/qtglobal.html#qt_set_sequence_auto_mnemonic.
 An easy workaround for this is to simply delete both occurances of 'qt_set_sequence_auto_mnemonic' in the __main__.py file, located at /usr/lib/python3/dist-packages/vidcutter/__main__.py (as also written in the errortrace).

I did that, but then another error appears:
 AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'
 In Result: Vidcutter still doesn't start..

I ran into the exact same problem. However, flatpak did not work for me on Ubuntu 16.04, snap didn't work either.

Thanks to the whole thread, I managed to make vidcutter 6.0.0 work by:

Installing vidcutter via apt

sudo pip3 install --upgrade PyOpenGL (which upgraded my version from  PyOpenGL-3.0.2 to  PyOpenGL-3.1.0)

Commenting out the following lines (at /usr/lib/python3/dist-packages/vidcutter/main.py) as they didn't let vidcutter start:
 #from PyQt5.QtGui import (QCloseEvent, QContextMenuEvent, QDragEnterEvent, QDropEvent, QGuiApplication, QMouseEvent,QResizeEvent, QSurfaceFormat, qt_set_sequence_auto_mnemonic)
 #qt_set_sequence_auto_mnemonic(False)
 #app.setDesktopFileName(vidcutter.desktopid)


I aslo managed to open vidcutter by doing the above said changes except I did not comment the below mentioned line completely, I just removed 'qt_set_sequence_auto_mnemonic' from the arguments and it worked:

from PyQt5.QtGui import (QCloseEvent, QContextMenuEvent, QDragEnterEvent, QDropEvent, QGuiApplication, QMouseEvent,QResizeEvent, QSurfaceFormat)

**Comment by dacbian** [comment]
@funkybunky have the corect solution, i tested in Debian 11, Mate desktop,Vidcutter 3.0.1
Just install python3-pip with Synaptic or in terminal.      sudo apt-get install python3-pip
