### ISSUE TITLE
VidCutter-3.0.0-linux-x64.AppImage is downloaded as .bin

### ISSUE THREAD

**Issue by omega3** [ozmartian/vidcutter#19]
It might be confusing for some users. 

I just change extension from bin to AppImage and run it like this (just for the record):
./VidCutter-3.0.0-linux-x64.AppImage

**Comment by ozmartian** [comment]
thats not anything i can control unfortunately... it must be the browser or o/s distro you're using.. what are you on? when i click to download AppImage from either KDE Plasma 4 & 5, Fedora, openSUSE, CentOS, Ubuntu (Yakkety & Trusty) they all save it correctly.

its probably that your system doesn't not have the .AppImage file extension associated/registered yet so it attempts to figure out what the file type is by looking at file headers, seeing its a binary and choosing .bin
