### ISSUE TITLE
PC-cillin detect virus ??

### ISSUE THREAD

**Issue by kodomoyeh** [ozmartian/vidcutter#195]
I used VidCutter-6.0.0-setup-win64.exe
and my PC-cillin detect ransomware 
it list that vidcutter want to crypt some jpg file under C:\Users\XXXXXX\AppData\Local\Temp

**Comment by yeahse** [comment]
really?

**Comment by juvabien** [comment]
![image](https://user-images.githubusercontent.com/5540508/80256913-0b324080-8680-11ea-993b-8c146748bdee.png)


I confirme via bitDefender

**Comment by alpenandrew** [comment]
![image](https://user-images.githubusercontent.com/6867231/98515275-ac00db80-221f-11eb-9f2f-8742fae9e78b.png)

**Comment by ozmartian** [comment]
Hi there,

Those virus programs are horrible and inaccurate and unnecessary in my opinion. More trouble than they are worth and the built-in Windows protection in 2020 is all you need but everyone has their opinions.

Anyway, that temporary folder is where the thumbnails shown in the timeline are stored once you open a video file and they are generated. Nothing malware-like about it, typical application process, storing temp files in the standard temp folder paths. Why these virus apps think its malware is beyond me. This is not a bug.
