### ISSUE TITLE
English operating system - Chinese Vidcutter

### ISSUE THREAD

**Issue by baimafeima** [ozmartian/vidcutter#199]
I run an English operating system but I want Vidcutter to be displayed in Chinese. Is this possible? How can I find and change these settings?

**Comment by mikhailnov** [comment]
You should use POSIX `LANG` environmental variable, but it will work only with programs which have translations, Vidcutter is availiable in English only.

**Comment by baimafeima** [comment]
I thought Vidcutter is widely translated. Are there any plans to make it more widely available?

**Comment by ozmartian** [comment]
English only atm... the next major update will use Qt language resource files starting with English and then you guys can all easily add your own translation files to get it working as you like... I'll make sure to include easy to follow instructions for this but I cannot commit to any timeframe right now.. probably ready in a month or so....

**Comment by ovari** [comment]
https://github.com/ozmartian/vidcutter/issues/148
