### ISSUE TITLE
Doesnt work on ubuntu 16.04

### ISSUE THREAD

**Issue by Gibbz** [ozmartian/vidcutter#2]
gui loads, but opening a video just crashes.

log  from command line:

vidcutter
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vidcutter/vidcutter.py", line 739, in handleError
    self.startNew()
  File "/usr/lib/python3/dist-packages/vidcutter/vidcutter.py", line 688, in startNew
    self.initNoVideo()
  File "/usr/lib/python3/dist-packages/vidcutter/vidcutter.py", line 208, in initNoVideo
    self.novideoWidget.setBackgroundRole(QPalette.Dark)
RuntimeError: wrapped C/C++ object of type QWidget has been deleted
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vidcutter/vidcutter.py", line 739, in handleError
    self.startNew()
  File "/usr/lib/python3/dist-packages/vidcutter/vidcutter.py", line 688, in startNew
    self.initNoVideo()
  File "/usr/lib/python3/dist-packages/vidcutter/vidcutter.py", line 208, in initNoVideo
    self.novideoWidget.setBackgroundRole(QPalette.Dark)
RuntimeError: wrapped C/C++ object of type QWidget has been deleted

**Comment by EarBiteR** [comment]
On linux mint 18.1 (ubuntu 16) I found it was missing libgstmediaplayer.so and throwing this error so fixed it by installing libqt5multimedia5-plugins

**Comment by muzena** [comment]
@EarBiteR Can you open mkv files?
On linux mint 18.1, when I try open mkv file, vidcutter it crashes

**Comment by ozmartian** [comment]
@Gibbz 

I fixed this issue after doing some testing with fresh installs of Ubuntu 16.04 via VM. The code was fine but was missing a few additional dependencies to make the QMediaPlayer component work properly. Its all so badly documented but I'm quite confident its all okay now.

This is all assuming you guys have been installing via PPA at:

    ppa:ozmartian/apps

If you upgrade/install the latest build from there it'll then download the necessary libraries to make it all work. Mainly it was a few gstreamer1.0-plugins packages and a qt5 (non-python) library which fixes the "No service" error.

Only issue I hav found is with Debian 8 (Jessie) which is so damn old and still on Qt5.3 which supports and older version of gstreamer. Definitely not worth worrying about that one.

Anyways, let me know how you go with the latest PPA build and thanks for the feedback etc! I've tested Ubunty Vivid and up as well as on Mint 18/18.1 with it all behaving well.

I'm an Arch user myself, this being my first attempt at a DEB so stick with me :-) It should be rocking now.

**Comment by ozmartian** [comment]
@muzena 

If you still experience some videos, lik MKVs in particular, not working after updating to the latest release then I'd recommended making sure your have **ubuntu-restricted-extras** installed which you probably do have but maybe things are broken so a reinstall couldn't hurt.

I basically loaded up a live CD of Ubuntu 16.04 and installed nothing but the PPA DEB and MKVs, H264 MP4s etc were all working as they should. Hope the same occurs for you now.

Thanks!
Pete

**Comment by muzena** [comment]
@ozmartian 
It works now, problem was in my .mkv files premissions, root:root, i change it to $USER:$USER

**Comment by Gibbz** [comment]
yep all working now....

Only other minor issue is if you dont put an extension on the video when saving is reports that it has output the file, but infact it does not...

**Comment by ozmartian** [comment]
Will take a look as its definitely including the extension in the code and it works in KDE, Windows and macOS so its a Ubuntu things. I'll look into it to see what can be done.

Thx for reporting that, I tested in Ubuntu already but didn't pick that up.

**Comment by ozmartian** [comment]
AppImage available as of v2.5.0
