### ISSUE TITLE
I can't access all locations to open a file

### ISSUE THREAD

**Issue by omega3** [ozmartian/vidcutter#20]
vidcutter see only etc, home, lib, usr folders on root partition.
I can't access additional partition that is mounted to /media folder

**Comment by ozmartian** [comment]
@omega3 

thanks for writing in.... i cannot replicate this myself, all mounts are visible and accessible.. the app uses your native file select so it would be a file choose dialog from Gnome, KDE, Unity, Mint etc...

let me know what distro, the version, your desktop manager and also confirm if your using the AppImage or PPA/repo package

should be able to work this out once i have those details.

cheers!
Pete

**Comment by omega3** [comment]
With version installed from PPA it sees every location, it is ok. 

AppImage doesn't see all locations on KDE Neon - plasma 5.9.3 developer stable version and on Kubuntu 14.04.
