### ISSUE TITLE
Export freezes at 50% [could not open codec]

### ISSUE THREAD

**Issue by Platypants** [ozmartian/vidcutter#218]
Hi, I'm a new user. I'm running Ubuntu 18.04.2 with Vidcutter 6.0.0. When I attempt to export my cuts with "Save Media", the progress bar jumps to 50% and then freezes there. I'm forced to quit the program. I have tried this with mp4s and flvs of varying lengths with the same results. The only possible clue I see in the console window is "[vd] Could not open codec."

**Comment by xcjiang** [comment]
same issue here, closing SmartCut may fix it.

**Comment by gwarah** [comment]
Same issue but sometimes in 66%. Attached a screenshot


$(uname -a)=Linux4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
install: snap
version: 6.0.0


![vidcutter_01_2019-03-03 11-34-27](https://user-images.githubusercontent.com/5703210/53696759-2de10600-3da9-11e9-989a-6311b6e3231d.png)

**Comment by etencore** [comment]
I confirm this conversion problem after "save" which blocks around 60% (with DV files)
The problem does not occur if "frame accurate cutting" is not enabled.
This problem may be similar to report #218 (Export freezes at 50%[could not open codec])
Version: 6.0.0 - Flatpack
System: Linux Mint mate 18.3 64bit

**Comment by etencore** [comment]
This problem may be similar to report #212 (Edited Video cannot save properly)
In the case of problem #212, it does not occur if "frame accurate cutting" is not enabled.
Version: 6.0.0 - Flatpack
System: Linux Mint mate 18.3 64bit

**Comment by danaivehr** [comment]
Have the same issue.

It seems the clue is 
```
2020-05-04 19:01 - root - CRITICAL -   File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 1392, in saveMedia
    self.joinMedia(filelist)
  File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 1452, in joinMedia
    self.complete(True, filelist[-1])
  File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 1460, in complete
    self.videoService.finalize(self.finalFilename)
  File "/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 283, in finalize
    self.checkDiskSpace(source)
  File "/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 162, in checkDiskSpace
    spacewarn = VCMessageBox('Warning', 'Disk space alert', warnmsg, self.parentWidget())

2020-05-04 19:01 - root - CRITICAL - <class 'AttributeError'>: 'VideoService' object has no attribute 'parentWidget'
```

It tries to show a dialog about Disk space and fails.
For me it happens if there is no info on free space - my video is on the mounted virtual drive.
If i try to cut the video from ordinary location, there is no any error.

**Comment by gwarah** [comment]
> This problem may be similar to report #212 (Edited Video cannot save properly)
> In the case of problem #212, it does not occur if "frame accurate cutting" is not enabled.
> Version: 6.0.0 - Flatpack
> System: Linux Mint mate 18.3 64bit

I've tried to convert with this configuration and the problem still remains. 

System ubuntu 16.04 LTS 64 bits

**Comment by Choupinounours** [comment]
I think i had a similar issue, and i gave the solution i found, here : https://github.com/ozmartian/vidcutter/issues/337#issuecomment-1077901923

Maybe it will help you...
