### ISSUE TITLE
produces zero-length files with VOB container

### ISSUE THREAD

**Issue by felagund** [ozmartian/vidcutter#23]
I got some VOB files from a DVD rip and I wanted to cut them up. They loaded just fine but when I tried to save them, a file got created that was zero-length. When I losslessly ocnverted the VOBs to mp4, I had no problems cutting them up using vidcutter.

**Comment by felagund** [comment]
MOV also behaves the same, mkv works correctly.

**Comment by cas--** [comment]
This sounds the same as my issue #26

**Comment by felagund** [comment]
Yes.

**Comment by ozmartian** [comment]
Can you guys let me know how this handles with the latest 3.2.0 release as considerable time was spent testing with various formats, including VOBs. Even with slightly corrupted versions too and improvements were made.

Thanks

**Comment by felagund** [comment]
Yes, both mov and VOB work.

**Comment by ozmartian** [comment]
awesome.. thanks for testing again
