### ISSUE TITLE
More keyboard shortcuts

### ISSUE THREAD

**Issue by felagund** [ozmartian/vidcutter#24]
Ideally, the app would use the same shortcuts that mpv itself uses for playback (detailed here: https://github.com/mpv-player/mpv/blob/master/etc/input.conf ideally including user customization in ~.config/mpv/input.conf), but I am mainly missing something that would go roughly 10 frames and about 2,5 seconds. Ideally one could set the concrete times and shortcuts oneself.

**Comment by ozmartian** [comment]
@felagund i'm looking at expanding the small settings menu to a proper dialog to allow for more options... i've intentionally limited shortcuts to avoid inteference and retain control of what goes on between mpv backend etc... what you have suggested is good though, i am thinking the simplest way forward is to have three levels of frame stepping / seeking in each direction... the first remains as one single step and the next two are configurable so can set the number of seconds forwards and backwards with the up/down and shift + up/down keys, currently fixed at 2 an 5 seconds.. 

it'll be in the next version

**Comment by felagund** [comment]
That would be great, can'T wati to test it!

**Comment by ozmartian** [comment]
its all done.. just going to add one other new feature and release within a day or two so wont be long
