### ISSUE TITLE
Support repeated cutting of a clip

### ISSUE THREAD

**Issue by felagund** [ozmartian/vidcutter#25]
Use case: I need to cut a clip into five parts. Right now, I have to restart the app, reload the video, find where the end of the last clip was, set is as as start, then set the end and cut as many times as I need to cut it. I think this workflow could be improved (by not closign the app after cutting, but if there were an option that would allow me to set multiple points A and B and then would cut multiple files at once, that would be great!

**Comment by felagund** [comment]
Oh sorry, that is already easily possible:-).

**Comment by felagund** [comment]
I thought it wa spossible but I can select multiple parts to combine into one video, but I would liketo produce more separate videos.

**Comment by ozmartian** [comment]
@felagund 

The latest 3.2.0 has a new option "Keep individual clips" in the settings menu which solves half of the problem you describe. I've also changed the clip complete dialog (the one saying "Your media is ready") to include a Continue button which is also selected by default so you can continue working on the same file.. You can reorder the clips with drag and drop on the mouse.

I think I am missing something in your description. If the clips are from the same source then all is now done for you with 3.2.0. Let me know if this is the case.

Cheers

**Comment by felagund** [comment]
Sounds great, the keep individual clips works great, thanks, and the "continue" option sounds even better

**Comment by ozmartian** [comment]
the continue button change + your suggested configurable seek time are all done and will be in tomorrow's release (or maybe the day after if time is against me)

cheers!
