### ISSUE TITLE
voice audio downloaded from Telegram couldn't be opened with Vidcutter 6.0.0 appimage?

### ISSUE THREAD

**Issue by AceHW** [ozmartian/vidcutter#266]
I wanted to use Vidcutter 6.0.0 appimage on MX Linux (which is based on Debian) (I'm using kde plasma instead of MX default of xfce) to join together some voice notes/messages I downloaded from Telegram desktop but Vidcutter can't seem to figure out how to open them. 

According to MediaInfo, they are opus audio in ogg container. 
I can play them in VLC, MPV, Audacity, Clementine, SM player, and Dragon Player, which are all the players I've tried them in. 

I've encoded flac audio files to ogg opus and ogg vorbis to see if those would play in Vidcutter and they did. I assume this means Telegram is doing something slightly unusual but not too unusual with their voice audio messages for them to not be recognized/playable by vidcutter when vidcutter can play ogg vorbis and ogg opus just fine, but not Telegram's encodings when telegram's encodings can be played by other players. 

[voice_audio_from_telegram_.zip](https://github.com/ozmartian/vidcutter/files/4234863/voice_audio_from_telegram_.zip)

Out of everything, I think opus audio should be one of the easiest things to combine with another sample file of itself without reencoding; pretty sure opus is made to be able to combine packets of different sizes and random opus streams together smoothly

I did notice that according to MediaInfo its encoder was fixed-point (if I'm understanding it correctly? pleace check the files with mediainfo yourselves), idk if that has anything to do with it not being recognized 

If you would recommend another gui application for cutting audio together without reencoding, please let me know (I know Vidcutter is obviously meant for cutting video of the exact same kind together), preferably something available on the Debian repo(s) and/or as an appimage (I really like appimages)

**Comment by ozmartian** [comment]
Please try v6.0.5.1 Flatpak, Snap or Launchpad PPA (recommended). AppImage is no longer supported for new versions until further notice.

**Comment by AceHW** [comment]
aw appimage is my favorite

**Comment by ozmartian** [comment]
:+1: If all goes smoothly I should be able to get a new AppImage for 6.0.5.1 built in a few days.

**Comment by AceHW** [comment]
oh good thanks

**Comment by AceHW** [comment]
that appimage isn't even executing/launching for me

I'm currently on AVLMXE (AV Linux, MX Edition), which is based on MX Linux
with some added tools from AV Linux, and uses a low latency kernel

the 6.0.0 appimage still launches but doesn't work with the file, whereas
that new appimage isn't even launching so I can't test if it works with the
file

**Comment by AceHW** [comment]
Update: I installed the flatpak of 6.0.5.1 and it still doesn't recognize
audio by itself as valid media, and I tried opus and flac and mp3, and it
wouldn't recognize any of them by themselves

Maybe this is by design? It is called vidcutter and not audiocutter or
something like that

I'd like to be able to cut audio without reencoding the whole thing

**Comment by ozmartian** [comment]
You're correct, cutting plain audio is outside of the app's design as it depend on there being a primary video stream. It's not too hard to modify the code to support plain audio cutting & joining. I'll add it to my list of potential future updates.
