### ISSUE TITLE
Flatpak 6.0.0 stalls at 50%

### ISSUE THREAD

**Issue by ManchoBlanko** [ozmartian/vidcutter#267]
When exporting/saving a large clip (actually the first and only clip I tried) Vidcutter hung at 50%.

**Comment by ManchoBlanko** [comment]
Forgot to mention I'm using MX Linux (MX-19)

**Comment by jleppert** [comment]
Have the same issue here, it froze at 50%. No video file created, no feedback to the user. Had to kill it. 
![froze](https://user-images.githubusercontent.com/120971/77238785-cacb3880-6b90-11ea-9fbd-e35ac13ca0b4.png)

**Comment by ManchoBlanko** [comment]
Hi Johnathan

I'm thinking of ditching Handbrake and Vidcutter in favour of using Kdenlive to trim and render source files directly to smaller mp4s.

Regards

Dave.

-------- Original Message --------

**Comment by new-on-github** [comment]
Same on Flatpak 6.0.7 here

**Comment by ozmartian** [comment]
Please retry with updated flatpak 6.0.5
