### ISSUE TITLE
Localisations needed

### ISSUE THREAD

**Issue by jdmuys** [ozmartian/vidcutter#274]
Hi, I would need a French version for my French family who doesn't speak English. I am ready to help to provide the French strings, and perhaps even some software development, but I would need some pointer on how to proceed.

**Comment by jdmuys** [comment]
I cloned the project, and was not able to build it. I could not find any instructions to that effect.

**Comment by ozmartian** [comment]
Check the newly added instructions on the main page re **Running from Python Source**. On macOS I'd recommend using Homebrew to install a working needed packages:

- pyqt@5
- ffmpeg
- mpv

Once that is installed, use pip to install python deps and run the application in a terminal within the source code folder:

```
$ pip install pyopengl simplejson
$ python3 setup.py build_ext -i
$ python3 -m vidcutter
```
