### ISSUE TITLE
Support for multiple output files

### ISSUE THREAD

**Issue by cansik** [ozmartian/vidcutter#28]
As a Visual Artist I have often the problem that I want to split a clip into multiple parts. For example a music video into some loops which I can use as independent visuals then.

It would be great if you would support a multi-video output button. This would save all the clips I've marked, into a new file.

**Comment by ozmartian** [comment]
Hi @cansik,

The recent version 3.2.0 included a new option in settings menu labelled "Keep indiviual clips" which I think is what you are after. All th clips you set to make your final video are kept along with the final, in the same target folder and named sequentially...

Let me know if I am mistaken...

**Comment by cansik** [comment]
It sounds like this would be the feature I needed. But I can't check it at the moment, because the vidcutter is always freezing after some seconds after I've loaded a video (and scrolling around in it).

**Comment by ash-f** [comment]
>new option in settings menu labelled "Keep indiviual clips"

Where is this option?

**Comment by cansik** [comment]
Very nice, the feature works. It is called `Keep clip segments` now and you can find it here:

<img width="702" alt="screenshot 2019-01-01 at 20 50 28" src="https://user-images.githubusercontent.com/5220162/50575903-03a1b500-0e07-11e9-9ccb-8149064d27f4.png">

**Comment by ash-f** [comment]
Hi, I'd like to split the video into multiple files but single file with index.
This option seems to export  single file regardless of on/off.
Am I understanding wrong?

**Comment by ash-f** [comment]
Sorry, I was understanding wrong.
I confirmed that it's possible to export multiple files.
