### ISSUE TITLE
Doesn't launch!

### ISSUE THREAD

**Issue by gb-dursley** [ozmartian/vidcutter#284]
Linux Mint 18.3. Vidcutter v. 5.0 installed via Mint's Software manager.  Icon appears in Menu.  Launch from Menu, Software Manager, or 'Open with..' for a specific video file; all fail, spinning wheel and flickering HDD led for a short period then nothing, nada, zilch!  Remove then Install gain (twice over!).  Makes no difference.  Absolutely nothing happens.

Even tried the Windoz trick - shutdown and cold boot.  Still nothing.
All I want to do is to cut down a number of AVI video clips from my 'trail camera' leaving just the short bits that actually show the night visitors to our garden.

**Comment by ozmartian** [comment]
Please try v6.0.5.1 via Snap, Flatpak or even better, the Launchpad PPA and re-open/comment. Thx!
