### ISSUE TITLE
Works great! Build from source, packages are out of date. Ubuntu 20 

### ISSUE THREAD

**Issue by kanoalani** [ozmartian/vidcutter#289]
I see a lot of open issues and grumpy comments. I'm confirming that **vidcutter does work**, and it's amazing! I edit and organize video fairly often using FOSS and pro software on both Linux and MacOS. I've been searching for a simple fast tool for basic timeline crops for a long time, and I haven't found anything until this. Vidcutter does the job:  clip sections of video directly from a video file without (pre-)(de-)(re-)encoding media. It's simple but **Excellent**, so don't let the commentary discourage you.

The repo hasn't been updated in a while but **that's OK**, it still works but every packaged distribution I tried was broken, **you have to build the application yourself**  The developer left clear and easy instructions in the Readme. 

Tested on _three different Linux computers_  with recent, ordinary and slightly different hardware/SW. Same result on each of them:

-  all of the package distributions I tried are broken (I tried several, not all). 
-  clone/build/install according to instructions works 100%

**Comment by DanielSiepmann** [comment]
I might be stupid, but where exactly do I find the build instructions? The readme only provides info about installation through package managers.

Snap works, but I've the issue that it runs out of disk space … I'm also not a fan of Snaps and therefore want to build the app myself.

That's what I came up with:

Install this list of dependencies (on ubuntu 20.04) using `sudo`:
```
apt install python3-pyqt5 libmpv-dev ffmpeg mediainfo python3-setuptools python3-pyqt5.qtopengl
easy_install pyopengl
```
Then build the app:
```
wget https://github.com/ozmartian/vidcutter/archive/master.tar.gz
tar zxf master.tar.gz
rm master.tar.gz
cd vidcutter-master
sed -i "s/pypi/rpm/" "vidcutter/__init__.py"
sudo python3 setup.py install
```

**Comment by kanoalani** [comment]
Good point, the instructions aren't actually in the README! It's mostly about package management; and they're helpful notes it's just that the packages haven't been updated in a long time. Here's what I did (literally, not intended as general-purpose instructions):

```
sudo apt-get install libmpv-dev mpv
cd /opt   
git clone https://github.com/ozmartian/vidcutter.git
python3 setup.py build
sudo python3 setup.py install
```
What was the reason for the 'sed' command? Our install procedure looks similar though you omitted the 'build' step. It should be implied as a dependency by 'install' but that means the build will run as sudo, which might make a difference depending on your environment.  Cloning vs tarball shouldn't make any difference.

Any video editor must have hardware and OS dependencies I'm using mostly Ubuntu 20 with intel integrated graphics on 1-3 yr old computers. On one laptop it exports significantly faster than another, the only hardware difference is the generation of i5 CPU so it may be a difference in how I installed dependencies? 

After using it extensively for a while I have run into actions and combinations of actions that cause it to hang. Seems to be different on each system and frankly I've never met a video editor that doesn't do that occasionally, it still gets the job done. In general I've had more consistent results from launching a new instance for every 'cut' as opposed to re-using a session by opening a new segment.

**Comment by wanted0** [comment]
I built a package for Ubuntu 20.04 based on the latest package source code, if anyone's interested:
https://github.com/wanted0/vidcutter-ubuntu20.04/raw/main/vidcutter_6.0.0-5%7Eubuntu20.04_amd64.deb

No changes done besides adding a note in changelog.

**Comment by ozmartian** [comment]
Launchpad PPA now supports Ubuntu Focal (20) and above plus updated to latest 6.0.5 version.
