### ISSUE TITLE
Fedora 33: dnf copr enable fails

### ISSUE THREAD

**Issue by dodona2** [ozmartian/vidcutter#292]
sudo dnf copr enable suspiria/VidCutter
-->
Error: This repository does not have any builds yet so you cannot enable it now.

**Comment by ozmartian** [comment]
Try United RPMs at https://unitedrpms.github.io and https://github.com/UnitedRPMs/unitedrpms

**Comment by ozmartian** [comment]
FYI, copr repo has been updated to 6.0.5.1 for Fedora 34 and Rawhide

https://copr.fedorainfracloud.org/coprs/suspiria/VidCutter
