### ISSUE TITLE
Error: "OpenGL context not initialized"

### ISSUE THREAD

**Issue by theelectricsoul** [ozmartian/vidcutter#293]
**What I did**
See [video](https://www.youtube.com/watch?v=0kSJNufImCQ)

**Here is my [log](https://bin.snopyta.org/?57114eb3371e97d9#7ayX4FXiMMj3BhqGGdHokLpDmzmjMSxGuXdLnbk1aMVr)**

**My system**
Running Windows 10 Pro. 

**Excerpt of the log file**
`[vo/opengl-cb] OpenGL context not initialized.
[cplayer] Error opening/initializing the selected video_out (--vo) device.
`

Thanky a lot for your awesome tool :)

**Comment by ozmartian** [comment]
update to version 6, i see you're on 5.5.0
