### ISSUE TITLE
Ubuntu 20 support

### ISSUE THREAD

**Issue by lenik-covert** [ozmartian/vidcutter#295]
Using your software for a few years and very happy with it. Recently upgraded to Ubuntu 20.

Trying to install and getting `This PPA does not support focal` message.

Could you please rebuild and distribute the packages for Ubuntu 20 ?

Thanks in advance!

**Comment by lenik-covert** [comment]
ok, for everyone who likes to install VidCutter from the repo in Ubuntu 20, here's the recipe:

1. clone the repo: `git clone https://github.com/ozmartian/vidcutter.git`
2. install deps: `sudo apt-get install libmpv-dev python3-pyqt5`
3. sommore deps: `sudo pip install -U pyopengl`
4. build time: `cd vidcutter; python setup.py build`
5. setup: `sudo pip install .`

Obviously, if something goes wrong at step 3, don't proceed to step 4 :face_with_rolling_eyes: (edited)

**Comment by shelleyfrank** [comment]
Thanks! In my case step 4 is `python3 setup.py build`
and step 5 is `sudo python3 -m pip install .`
Vidcutter installs and runs without errors. I'm on Linux Mint 20.

**Comment by lenik-covert** [comment]
@shelleyfrank I'm on mint20 as well, you might have not installed `python-is-python3` package which simplifies things a bit.

**Comment by uali6981** [comment]
Thanks! In my case step 5 is sudo python3 -m pip install /home/USER/vidcutter.
Vidcutter installs and runs without errors. I'm on Ubuntu 20.04.

**Comment by ozmartian** [comment]
Please retry PPA. Packages updated for VidCutter 6.0.5 and now serving focal and above.
