### ISSUE TITLE
Request: Introduce seeking by keyframe

### ISSUE THREAD

**Issue by theelectricsoul** [ozmartian/vidcutter#297]
From experience, using media players like Potplayer, which allow seeking by key frames, allow very fast seeking.

**Request**
Please introduce seeking by keyframes :) Maybe while holding down a hotkey.

Many thanks for this sweet piece of software :)

**Comment by ozmartian** [comment]
does the left and right key not work for you when a video is loaded?

**Comment by theelectricsoul** [comment]
Well....    left right keys seek frame by frame which is good, but a delay during seeking is noticeable. Seeking by keyframe is blazing fast without delay.

**Comment by ozmartian** [comment]
Got it. Unfortunately we're limited to what MPV allows as that is the video player library being used. VidCutter was always meant to be simple and lightweight for casual everyday users whereas when getting into frame by frame seeking and 100% keyframe cuts it gets complex and turns it into a proper video editor which it is not, reinveting the wheel. If I can find someway to implement this I will do in future.



Thanks for your support!




---- On Fri, 04 Dec 2020 10:44:36 +1100 theelectricsoul <notifications@github.com> wrote ----




Well....    left right keys seek frame by frame which is good, but a delay during seeking is noticeable. Seeking by keyframe is blazing fast without delay.

**Comment by theelectricsoul** [comment]
Ohh  one more thing. Right now, Vidcutter splits at the nearest keyframe. But if users could seek by keyframe they would know where vidcutter would make the non accurate split.

**Comment by ozmartian** [comment]
Yep. Thats what the SmartCut feature is for, tries to solve this by reencoding start and end parts of clip while direct cutting the middle parts then assembling it. This takes MUCH longer and doesn't always work as intended depending on the source video. There are a few fixes to this to improve things coming soon.




---- On Fri, 04 Dec 2020 10:57:30 +1100 theelectricsoul <notifications@github.com> wrote ----




Ohh  one more thing. Right now, Vidcutter splits at the nearest keyframe. But if users could seek by keyframe they would know where vidcutter would make the non accurate split.

**Comment by ozmartian** [comment]
The mouse-wheel seeks by frame.
