### ISSUE TITLE
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow) & critical operation not implemented mpvwidget.py

### ISSUE THREAD

**Issue by slrslr** [ozmartian/vidcutter#299]
I have [Installed] Vidcutter 6.0.0-5  community (Arch Linux based Manjaro)

It failed to open mkv, avi, ts file, i have not tried other. No message, no playback.
[log file with errors here](https://bin.disroot.org/?0f5f8339d1d4346c#4CLeEFdQvCJtEcQQ439bkfSz4X7zkzXENm2AFjhthT42)
command line from which i launched vidcutter shows seemingly one error per each file open attempt:
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 10254, resource id: 9074862, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 10416, resource id: 9079722, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 13372, resource id: 9028245, major code: 40 (TranslateCoords), minor code: 0

**Comment by ozmartian** [comment]
the Arch package is still not updated as its on 6.0.0. latest version with fixes is 6.0.5. i've contacted the Arch package maintainers about this so just hang in there and they'll get it updated to 6.0.5 sometime soon. am keeping a watch and will remind them if nothing done soon.
