### ISSUE TITLE
Don't close the tool after choosing to save a clip

### ISSUE THREAD

**Issue by felagund** [ozmartian/vidcutter#30]
Often, I would liketo change something in the way I cut the clip. I ahve to set everything from scratch now. I can manage closing the window myself.

**Comment by SelfRando** [comment]
Agree. After saving the (very short) clip I want to review it in VLC and then maybe adjust the start and end points by 2/10th of a second.

Currently I have click the X on the dialog box which appears after saving but it would be better if there was a button for 'Continue'

**Comment by ozmartian** [comment]
@SelfRando @felagund 

Noted and will be resolved in the next version which should be out within a week or so. I was actually thinking exactly on these lines earlier today regarding the app's workflow.

Thanks!
