### ISSUE TITLE
Empty file with _FINAL appended is created

### ISSUE THREAD

**Issue by tastytea** [ozmartian/vidcutter#300]
When I save a clip with the filename “test.mp4”, 2 files are created: test.mp4 and test_FINAL.mp4. The latter is empty (0 bytes).

Version: VidCutter 6.0.0
OS: Gentoo Linux
Python version: 3.8.6

**Comment by ozmartian** [comment]
I can't support Gentoo unfortunately. Try running from a terminal:

```
$ vidcutter --debug <video_file>
```

and see if any missing libraries etc. are reported and we can work from there. Be sure to be on version 6.0.5.1 (latest Git HEAD is fine).

**Comment by tastytea** [comment]
I can't reproduce it with 6.0.5 anymore.
