### ISSUE TITLE
Will not run on Big Sur

### ISSUE THREAD

**Issue by jchhenderson** [ozmartian/vidcutter#301]
Hi,

Can some kind soul please explain how to install the latest version (6.05) onto macOS Big Sur?

thanks.

**Comment by applebait** [comment]
Latest version is 6.0.0 at least from what I see on the releases and also from homebrew. Either way, it doesn't even open, on Big Sur.

**Comment by jchhenderson** [comment]
6.0.0 is the latest release, but there is an unreleased 6.0.5 which fixes a few things - but you need to build it (or something).

**Comment by ozmartian** [comment]
Closing as being handled in another issue.
