### ISSUE TITLE
"Open Media" and "Save Media" consistantly trigger hard crash in Ubuntu 20.04

### ISSUE THREAD

**Issue by rtayrien** [ozmartian/vidcutter#317]
I have installed Vidcutter 6.0.5.1 (Snap) on my long stable fully patched Kubuntu 20.04 and Ubuntu Studio 20.04.  4 installs from 2 sources followed by restarts on each occasion. Installation was without incident and the interface launched without a problem.

When clicking "open media" the application immediately crashed on several attempts. No warning or recognition from Ubuntu

I could load a video file for edit from a file manager by selecting "Open With" > "Vidcutter". The file and app loaded appropriately and I could use the NLE tools to manipulate the file without difficulty. When clicking "Save Media" the app again crashed without display of a save dialogue. The file could be reopened in a similar fashion but edits were not persevered.   When I select "view log files" from the menu there is no response. 

It has been suggested EDL scripts should be updated but that is beyond my skill level. 

This has been recently reported on Vidcutter reviews on the KDE Discover package manager but it appears not in this forum.  There is a suggestion months ago on this forum that the packages had not been updated and one needed to build the app but the source and Readme file instructions seem to be elusive. 

Could you please validate, refute and/or update this issue.

Thanks

**Comment by ozmartian** [comment]
Thx for the feedback. I cannot replicate this myself but am guessing its a snap configuration issue I will need to look further into.
Out of curiosity, could you try running the AppImage https://github.com/ozmartian/vidcutter/releases/download/6.0.5.1/VidCutter-6.0.5.1-x86_64.AppImage and let me know if it works. Just download, set the file to executable and run.

**Comment by ozmartian** [comment]
Sounds like a Kubuntu issue with file open/save dialog windows since you can get it working when opening from file manager or from command line console. Hopefully fixed soon.

**Comment by rtayrien** [comment]
Thanks for your prompt response and helpful input. 

I had already posted this on the Ubuntu forum a couple of days ago.  Responses pointed me back to Vidcutter.  I think I failed to report that I also tried to run the app on Ubuntu Studio as a separate instance with same results.  (I.e. normal install but fail to load or save media from app).  

The following may also be revealing...

I did try running the AppImage version, per your suggestion, both from GUI file manager and command line.  Both failed to launch the app  but the latter generated the following message (full command line script also follows below for context):

```
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'
```

I notice that both Python 3 and 3.8 are installed in my usr>bin folder.  Could this error be related to a conflict, a config. error or would the message suggest that I have missing Python dependencies? 

Failing that would setting "verbose log files" to "ON" or otherwise changing the options settings within the app generate any other helpful information?

```
xxx@XXXLinuxWS:~$ cd Downloads
xxx@XXXLinuxWS:~/Downloads$ chmod +x VidCutter-6.0.5.1-x86_64.AppImage
xxx@XXXLinuxWS:~/Downloads$ ~/Downloads/VidCutter-6.0.5.1-x86_64.AppImage
Python path configuration:
  PYTHONHOME = '/tmp/.mount_VidCut5INMyA/usr/'
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/tmp/.mount_VidCut5INMyA/usr'
  sys.base_exec_prefix = '/tmp/.mount_VidCut5INMyA/usr'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/tmp/.mount_VidCut5INMyA/usr'
  sys.exec_prefix = '/tmp/.mount_VidCut5INMyA/usr'
  sys.path = [
    '/tmp/.mount_VidCut5INMyA/usr/lib/python38.zip',
    '/tmp/.mount_VidCut5INMyA/usr/lib/python3.8',
    '/tmp/.mount_VidCut5INMyA/usr/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f1eae233b80 (most recent call first):
<no Python frame>
xxx@XXXLinuxWS:~/Downloads$ >
```
Thanks again for the feedback.

**Comment by ozmartian** [comment]
Damn! Sorry to hear no luck. This is on my TODO list.

In the meantime, since you're on Ubuntu you could just use the official PPA. It works great for Ubuntu 20+ AFAIK.

`
sudo add-apt-repositoryppa:ozmartian/apps
sudo apt-get update
`

**Comment by rtayrien** [comment]
Perfect!  Installed flawlessly.  Opened the app pulled a clip had it trimmed saved in 30 seconds.  Launched the edited clip in VLC and it ran flawlessly!  Pulled the edit back into Vidcutter and did a second edit, same results.  

That's what I was looking for!!!

Thanks so much!  Your commitment is evident in this clean efficient little tool that really fills an important niche for those of us not making movies but building presentations and need to configure short video assets for education, presentations etc. 

If you ever need any help testing just ping me I am happy to contribute. 

Best Regards,

**Comment by ozmartian** [comment]
Thx mate and appreciate the kind words. Hopefully will get around to releasing a new version with more fixes and improvements soon. Cheers!
