### ISSUE TITLE
mpv has removed support for opengl_cb API and now vidcutter cannot compile

### ISSUE THREAD

**Issue by PhobosK** [ozmartian/vidcutter#345]
Hi MPV has already removed the support for the opengl_cb (https://github.com/mpv-player/mpv/commit/632059816adde518c67f6606e3cfdef5bec18b52) and now vidcutter doesn't compile:

```
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -fno-semantic-interposition -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -fPIC -I/usr/include/python3.8 -c vidcutter/libs/pympv/mpv.c -o build/temp.linux-x86_64-3.8/vidcutter/libs/pympv/mpv.o -g0
vidcutter/libs/pympv/mpv.c:630:10: fatal error: mpv/opengl_cb.h: No such file or directory
  630 | #include "mpv/opengl_cb.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

Tumbleweed already moved to the new libmpv2

Thanks

**Comment by easyteacher** [comment]
The package is going to be removed from Tumbleweed if it continues failing compiling.

**Comment by ozmartian** [comment]
VidCutter was updated and switched from opengl_cb to the new render API about 2 years ago. Perhaps there is some unneeded dependency in place somewhere.

I haven't tested compiling against mpv 0.35 but will do when I get some time.

**Comment by ozmartian** [comment]
Its an issue with pympv, a dependency. Should have this resolved sometime soon.

**Comment by ozmartian** [comment]
I've just pushed a new commit with 3 changes to files in the pympv libs folder. These are simple patches to get pympv working with latest. Have tested it against latest mpv-git code so should be all good.

Will let the OpenSUSE guys know. 👍

**Comment by easyteacher** [comment]
I have submitted a request for it. Thank you very much!

https://build.opensuse.org/request/show/956574

**Comment by ozmartian** [comment]
Champion. Thx!

**Comment by ozmartian** [comment]
Looks like the builds are going through. I dont have an OpenSUSE VM to test upon right now so hope it all executes without fail.

**Comment by easyteacher** [comment]
Tested, no problem cutting videos.

**Comment by ozmartian** [comment]
Awesome. Thanks so much for your help!
