### ISSUE TITLE
Vidcutter dependencies

### ISSUE THREAD

**Issue by bornagainpenguin** [ozmartian/vidcutter#354]
Tried to use my usual AppImage and it wasn't launching on Ubuntu-Mate 22.04 LTS beta.  Looked to see if I was behind a version and I was so I grabbed the more recent version and placed it in ~/.local/bin and tried again.  Still not working, I ran the command in terminal and got an error message that was listed here.  Tried removing the AppImage and installing from PPA, this time I got a dependency message:

```
The following packages have unmet dependencies:
 vidcutter : Depends: python3 (< 3.10) but 3.10.1-0ubuntu2 is to be installed

```

Any suggestions on how this can be resolved?  Thank you for the wonderful app.

**Comment by bornagainpenguin** [comment]
Attempting to use the AppImage instead resulted in nothing displaying after a few moments.  I copied the command from my applications menu into the terminal and was rewarded with this output:

```
Python path configuration:
  PYTHONHOME = '/tmp/.mount_VidCutlAeogb/usr/'
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/tmp/.mount_VidCutlAeogb/usr'
  sys.base_exec_prefix = '/tmp/.mount_VidCutlAeogb/usr'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/tmp/.mount_VidCutlAeogb/usr'
  sys.exec_prefix = '/tmp/.mount_VidCutlAeogb/usr'
  sys.path = [
    '/tmp/.mount_VidCutlAeogb/usr/lib/python310.zip',
    '/tmp/.mount_VidCutlAeogb/usr/lib/python3.10',
    '/tmp/.mount_VidCutlAeogb/usr/lib/python3.10/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f47346c5740 (most recent call first):
  <no Python frame>

```
Again, any advice appreciated and thanks for this wonderful application.

**Comment by lestcape** [comment]
Same here, but now in Ubuntu 22.04 LTS as is not a Beta anymore. Good to see a dependency update in consequence, as seem to be that if you force the installation, also when you have broken dependencies, the software works.

**Comment by bornagainpenguin** [comment]
One can only hope that Ubuntu 22.04 LTS no longer being in beta would mean that the issues here will be resolved soon.

**Comment by ozmartian** [comment]
AppImage is no longer supported unfortunately, unless I get the time to update and fix current issues with the build. Alternatively, Flatpak and Ubuntu PPA options are recommended depending on what distro you're on.

Have recently updated both the PPA, snap and flatpaks.
