### ISSUE TITLE
Fix for mpv-git

### ISSUE THREAD

**Issue by bulvara** [ozmartian/vidcutter#357]
Dear ozmartian,

may I change https://github.com/ozmartian/vidcutter/commit/4cf1458d832e6ac7a824d7963c6dc3a0e5c17574 back for my local build against mpv-git?

**Comment by ozmartian** [comment]
Of course. That is what fixes the issue with mpv-git. 



Edit mpv.pyx and delete mpv.c. It is regenerated by python setuptools or manually via:



$ python setup.py build_ext -i

Cheers,

Pete






---- On Sun, 22 May 2022 02:25:03 +1000 bulvara ***@***.***> wrote ----





Dear ozmartian,

may I change https://github.com/ozmartian/vidcutter/commit/4cf1458d832e6ac7a824d7963c6dc3a0e5c17574 back for my local build against mpv-git?
