### ISSUE TITLE
Files with extension MP4 don't appear in Open Media file dialog

### ISSUE THREAD

**Issue by jdalbey** [ozmartian/vidcutter#386]
The Open Media file dialog won't display files with an extension MP4 (upper case) when the "All media files" filter is chosen.  If the file is renamed with extension "mp4" (lowercase) then the file will appear.   It seems to me that the dialog should be smart enough to recognize the upper case file extension.

**Comment by ozmartian** [comment]
Are you perhaps using the Snap or Flatpak? Seems to be a Qt bug with the platforms at times. Are you able to enter "*.*" into the media type field?

You could also drag the source video onto your VidCutter icon or right-click -> open with -> VidCutter as a last resort. Not ideal I know.
