### ISSUE TITLE
Add cuts from a txt file with the start and end timecode of each cut.

### ISSUE THREAD

**Issue by Thiagobhmg** [ozmartian/vidcutter#389]
Could you add cuts from a txt file with the start and end timecode of each cut?

There is a huge potential to add AI-powered processing commands. It could transcribe a video with Whisper, generate the VTT, and allow the user to request the AI to select the best cuts from the subtitles and indicate the start and end of each cut in webvtt format. The system would then automatically process and generate a video, or even export each cut individually.

Congratulations on the project, one of the best I have ever used.

Edit: I got carried away with possibilities and forgot to mention the main request. 😅

It would be interesting if it were possible to load a file indicating the start and end time of each cut along with the video to be edited, and have the system automatically process it. I see many uses for something like this. Or even something that can be processed via command line.

**Comment by ozmartian** [comment]
Hi,



Not sure if this is what you are after but there is a "Save Project" option available in the Options menu button or right-clicking on the video player. This allow you to save project to a text file in a VidCutter custom format .vcp or a moire standardized MPlayer EDL. Both are text files you can video and edit in a text editor containing project file and timecodes.



Cheers,

Pete






---- On Tue, 08 Aug 2023 04:55:07 +1000 Thiago Franklin ***@***.***> wrote ---





Could you add cuts from a txt file with the start and end timecode of each cut?

There is a huge potential to add AI-powered processing commands. It could transcribe a video with Whisper, generate the VTT, and allow the user to request the AI to select the best cuts from the subtitles and indicate the start and end of each cut in webvtt format. The system would then automatically process and generate a video, or even export each cut individually.

Congratulations on the project, one of the best I have ever used.
