### ISSUE TITLE
Application won't start

### ISSUE THREAD

**Issue by AlexValue** [ozmartian/vidcutter#391]
I installed VidCutter on Fedora 38 silverblue in flatpak format, but the application crashes when I open it.

**Comment by ozmartian** [comment]
There was an issue with the recent Flatpak update but has been resolved. Try reinstalling in 8-12 hours as the flathub publishing cache takes time to update.






---- On Mon, 16 Oct 2023 10:05:30 +1100 Alexander Valiukh ***@***.***> wrote ---





I installed VidCutter on Fedora 38 silverblue in flatpak format, but the application crashes when I open it.
