### ISSUE TITLE
Git clone & install results in---  ImportError: libmpv version is incorrect. Required 2.0 got 1.109.  Missing AAC audio track leads to hang at 66% on save.

### ISSUE THREAD

**Issue by mythtvuser** [ozmartian/vidcutter#393]
After installing vidcutter (using snap on Ubuntu 22.04) It would hang on attempting to write out file.
Searching for existing fixes resulted in the "hang at 60%" fault 
(a persistent issue concerning vidcutter's default temp file in /tmp by dates of prior instances).
**Uninstalled snap version and attempted local build from repo** (git clone etc. using **svonidze**'s reply from https://github.com/ozmartian/vidcutter/issues/171) 

A side issue was "pip not found" when attempting "sudo pip install -U pyopengl" (resolved with "sudo apt install python3-pip")

After "cd vidcutter" --- "python3 setup.py build" and "sudo pip install ." 
**running "vidcutter" gives result:**
Traceback (most recent call last):
  File "/usr/local/bin/vidcutter", line 5, in <module>
    from vidcutter.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/vidcutter/__main__.py", line 41, in <module>
    from vidcutter.videocutter import VideoCutter
  File "/usr/local/lib/python3.10/dist-packages/vidcutter/videocutter.py", line 57, in <module>
    from vidcutter.libs.mpvwidget import mpvWidget
  File "/usr/local/lib/python3.10/dist-packages/vidcutter/libs/mpvwidget.py", line 63, in <module>
    import vidcutter.libs.mpv as mpv
  File "vidcutter/libs/pympv/mpv.pyx", line 46, in init vidcutter.libs.mpv
    raise ImportError(
**ImportError: libmpv version is incorrect. Required 2.0 got 1.109.**

The snap install is a read-only filesystem, so attempts at editing/replacing files in snap install (suggested as fixes for the above elsewhere) would not work, hence all above.

EDIT:  (5 hours after above:) Uninstalled the above, installed flatpak of vidcutter. 
Result:  Back to original situation/issue -- 
(With frame accurate cutting de-selected) progress bars hit 66%, then freeze.
(With frame accurate cutting selected) after clicking "save media" --  no file save at all, progress bars remain at 0%. 
No rise in CPU activity in system monitor or htop indicating processing of cuts.

Advice given by others on previous requests seeking resolution of the above, suggest it concerns vidcutter's using /tmp in the system root for storing data during "save media" and that setting up an alternate /<user>/tmp file with a symlink was a workaround which needed to be re-applied after any system reboot.
If this is the case, perhaps a vidcutter config file where such options could be saved by users, taking account of their system configuration, would be appropriate.

System: Ryzen 5 4600, 32GB RAM, 2x1TB ssd (only 4% use of / so temp file space should not be an issue)...
vidcutter version 6.0.5.1 (from github page)

Looking (hoping) for a frame-accurate editor for h.264 content after using DVBCut on 720p Mpeg2 files.

**Comment by coffeemonk-exe** [comment]
How was the libmpv version incorrect error fixed? Can you elaborate?

**Comment by ozmartian** [comment]
In vidcutter/libs/pympv/mpv.pyx, lines 33-36. You'll see the previous version commented. Whenever changing this you need to also delete vidcutter/libs/pympv/mpv.c so that it regenerates when building or executing the project.

**Comment by ozmartian** [comment]
The code in the repo has been set to 2.0 for sometime so please let me know if all is okay so I can close this issue.
