### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by vertigo220** [ozmartian/vidcutter#396]
Would be nice to have a dark mode

**Comment by ozmartian** [comment]
Settings -> Theme -> Dark






---- On Sun, 21 Jan 2024 16:36:40 +1100 vertigo220 ***@***.***> wrote ---





Would be nice to have a dark mode

**Comment by vertigo220** [comment]
Wow, not sure how I missed that. Guess I was just so focused on other issues. Thanks.
