### ISSUE TITLE
Clarify what this program is. 

### ISSUE THREAD

**Issue by rexendevar** [ozmartian/vidcutter#403]
I downloaded this with the intention of cropping a video file (as in taking off a bit of the top and a bit of the bottom), and I'm very disappointed that I can't do that in this program. I think you should clarify in the readme file what this program is and does and doesn't do

**Comment by exciar** [comment]
cutting as in length not cropping which you are pertaining to, YOU ARE WRONG

**Comment by arjhun** [comment]
> I downloaded this with the intention of cropping a video file (as in taking off a bit of the top and a bit of the bottom), and I'm very disappointed that I can't do that in this program. I think you should clarify in the readme file what this program is and does and doesn't do

Why would programs have to advertise what they don't do? You're not going to add to that list baking an egg, writing an excel document or world peace right. Read the docs for God sake and respect the hard work that goes into these projects.

**Comment by exciar** [comment]
> > I downloaded this with the intention of cropping a video file (as in taking off a bit of the top and a bit of the bottom), and I'm very disappointed that I can't do that in this program. I think you should clarify in the readme file what this program is and does and doesn't do
> 
> Why would programs have to advertise what they don't do? You're not going to add to that list baking an egg, writing an excel document or world peace right. Read the docs for God sake and respect the hard work that goes into these projects.

The real issue is the user doesn't understand the difference between cutting and cropping, it is truly that "Users can't read, Users can't remember, Users can't control".
