### ISSUE TITLE
Vidcutter pip3 install in Fedora 25 : Requirement error

### ISSUE THREAD

**Issue by didli** [ozmartian/vidcutter#6]
Hi ! I'm trying the pip3 install, but I can't get very far since it returns this error :
`Collecting PyQt5>=5.5 (from vidcutter)
  Could not find a version that satisfies the requirement PyQt5>=5.5 (from vidcutter) (from versions: )
No matching distribution found for PyQt5>=5.5 (from vidcutter)`
As little as I understand this, something about PyQt5 should be included but it's not yet provided ?
Thank you for your help !

**Comment by ozmartian** [comment]
Hi there. Its basically saying it cannot find the PyQt5 library. You can easily fix this with:

    sudo pip3 install PyQt5

BUT its not recommended as Fedora will have their own version of the library available as a native Fed package. I'm planning on producing a Fedora specific install ASAP, also an AppImage release which will work in all distros.

If you are a little python savvy and you dont want to install PyQt5 via pip3 (as it "may" conflict with other Fedora package that use it in the worst case but I doubt it). You could try a virtual environment and install the Pypi version of PyQt5 there along with vidcutter:

`
$ sudo pip3 install virtualenv
$ virtualenv -p $(which python3) $HOME/vidcutter
$ cd $HOME/vidcutter
$ source bin/activate
$ pip3 install vidcutter
$ vidcutter
`

that will install vidcutter and its dependencies in a folder 'vidcutter' under your home directory without touching your system's libraries so its safe. I'd recommend this approach until I've got a Fedora built & tested install ready (hopefully in a couple of days)

**Comment by didli** [comment]
Now pip is being funny :
`sudo pip3 install PyQt5
Collecting PyQt5
  Could not find a version that satisfies the requirement PyQt5 (from versions: )
No matching distribution found for PyQt5`
But anyway, if you're planning a Fedora package or an Appimage, it's perfectly fine with me, I will wait for it and I thank you for this !

**Comment by Vienna550** [comment]
Hello everybody and first of all let me say a big, big thank you to the developer of Vidcutter for such a great and easy to use tool to cut and edit TV-recordings. Regarding Vidcutter & Fedora 25: David Vasquez has already build an rpm-package of 2.2.5 and it is available via the unitedrpms-repo:
[http://unitedrpms.sourceforge.net/x86_64/repoview/vidcutter.html ](url)

If you are a little bit more adventurous, you can also give my testbuild of the 2.6.5 a try. The new version of vidcutter required some minor modifications of the spec-file. It's available here:
[http://paste.fedoraproject.org/545496/62128641/](url)

You can download the the rpm here: [http://www.filedropper.com/vidcutter-265-0fc25noarch](url) but you really shouldn't run possibly untrustworthy binaries and rpm's from some stranger ;-)

Therefore here's the download-link for the src.rpm: http://www.filedropper.com/vidcutter-265-0fc25src 
You can unpack or install the src.rpm in a build-environment (rpm i as user), then check the package and rebuild it with rpmbuild -ba vidcutter.spec

**Comment by didli** [comment]
Thanks, Vienna550 and David Vasquez. The unitedrpms RPM worked straight away. Vidcutter is damned fast. I've just tried a 64Mo ogv file, cutting 10 sec in both start and end of the video. It was so fast I though something went wrong ^^.
