### ISSUE TITLE
VidCutter AppImage not launching on Gentoo

### ISSUE THREAD

**Issue by taohansen** [ozmartian/vidcutter#78]
```
/tmp/.mount_VidCutOvhcTg/usr/bin/vidcutter.wrapper: line 121: 27116 Aborted                 (core dumped) LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" 2> /dev/null
/tmp/.mount_VidCutOvhcTg/usr/bin/vidcutter.wrapper: line 121: 27123 Aborted                 (core dumped) LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" 2> /dev/null
/tmp/.mount_VidCutOvhcTg/usr/bin/vidcutter.wrapper: /tmp/.mount_VidCutOvhcTg/usr/bin/vidcutter: /usr/bin/python3.5: bad interpreter: No such file or directory
/tmp/.mount_VidCutOvhcTg/usr/bin/vidcutter.wrapper: line 99: /tmp/.mount_VidCutOvhcTg/usr/bin/vidcutter: Success
```

**Comment by taohansen** [comment]
this is still not functional with the latest AppImage though the error message has changed:

`/tmp/.mount_VidCutE3DrNs/usr/bin/vidcutter.wrapper: line 121:  2748 Aborted                 (core dumped) LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" 2> /dev/null
/tmp/.mount_VidCutE3DrNs/usr/bin/vidcutter.wrapper: line 121:  2755 Aborted                 (core dumped) LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" 2> /dev/null
fish: “./VidCutter-4.0.0-x64.AppImage” terminated by signal SIGSEGV (Address boundary error)`

**Comment by ozmartian** [comment]
hi @taohansen,

i'll get myself a Gentoo VM installed here and take a look.. could you confirm whether AppImages in generally work on Gentoo cause I've seen them struggling under non-Debian based distros occassionally..

also, FYI... not sure if this even works but someone has but together a portage overlay you could try here: https://gpo.zugaina.org/media-video/vidcutter

**Comment by Generator** [comment]
Same with Archlinux
```
/tmp/.mount_VidCutrfogbH/usr/bin//vidcutter.wrapper: /tmp/.mount_VidCutrfogbH/usr/bin/vidcutter: /usr/bin/python3.5: bad interpreter: No such file or directory
/tmp/.mount_VidCutrfogbH/usr/bin//vidcutter.wrapper: line 103: /tmp/.mount_VidCutrfogbH/usr/bin/vidcutter: Success
```
AppImage depends on python3.5, on archlinux python=3.6.3

**Comment by taohansen** [comment]
@ozmartian switched to GuixSD/NixOS, which doesn't even have packages available for VidCutter so the problem is no longer relevant to me but i do appreciate you taking the time.

AppImages should work on most distros that conform to the Filesystem Hierarchy Standard (which NixOS/GuixSD do not).

feel free to close this issue if no one else speaks up about it.
