### ISSUE TITLE
vidcutter-4.0.0 not launch on Fedora 26

### ISSUE THREAD

**Issue by martinkg** [ozmartian/vidcutter#79]
error on launching: ModuleNotFoundError: No module named 'OpenGL'
solution: install missing package with
`# dnf install python3-pyopengl`

**Comment by kn00tcn** [comment]
the rpmfusion package has pyopengl as a dependency on 25, feel like its date is 0-2 days after this thread, do we mark it 'fixed'?

**Comment by martinkg** [comment]
thread could be closed, i am the package maintainer of the vidcutter rpmfusion package.
