### ISSUE TITLE
Doesn't launch on Debian 9 (stretch)

### ISSUE THREAD

**Issue by mobafan** [ozmartian/vidcutter#87]
VidCutter 4.0.0 AppImage does not start with Debian 9 (stretch). No error messages.

**Comment by taohansen** [comment]
@ozmartian, what’s the point of an AppImage if they’re not self-contained
and self-executable? look, don’t take this the wrong way but between my
issue and all the others i see cropping up maybe you should consider
another distribution platform, like Flatpak or Snap?
