### ISSUE TITLE
vidcutter won't startup

### ISSUE THREAD

**Issue by TheFu** [ozmartian/vidcutter#9]
Ubuntu 14.04.5 install using the PPA.

```
$ vidcutter 

(python3:10440): GStreamer-CRITICAL **: gst_object_ref: assertion 'object != NULL' failed
Segmentation fault

```
Looked for a manpage - doesn't exist.
Tried adding more verbose output with -d and -vvv options. 
```
$ vidcutter -h

(python3:12326): GStreamer-CRITICAL **: gst_object_ref: assertion 'object != NULL' failed
Segmentation fault

```
Don't know where to begin.

**Comment by lafaurie** [comment]
I have an issue with the appImage in opensuse this is the output `/bin/bash: /tmp/.mount_Lt6h9B/lib/x86_64-linux-gnu/libreadline.so.6: no version information available (required by /bin/bash)
['/tmp/.mount_Lt6h9B/usr/bin', '/tmp/.mount_Lt6h9B/usr/share/pyshared', '/usr/lib64/python3.4/site-packages/PyQt5', '/data/Tools/Linux/Media', '/usr/lib/python34.zip', '/usr/lib64/python3.4', '/usr/lib64/python3.4/plat-linux', '/usr/lib64/python3.4/lib-dynload', '/usr/lib64/python3.4/site-packages', '/usr/lib64/python3.4/_import_failed', '/usr/lib/python3.4/site-packages']
Traceback (most recent call last):
  File "/tmp/.mount_Lt6h9B/usr/bin/vidcutter", line 5, in <module>
    from vidcutter.vidcutter import main
  File "/usr/lib/python3/dist-packages/vidcutter/vidcutter.py", line 13, in <module>
    from PyQt5.QtCore import (QDir, QFile, QFileInfo, QModelIndex, QPoint, QSize, Qt, QTextStream, QTime, QUrl,
ImportError: No module named 'PyQt5.QtCore'
`

**Comment by ChrisMayfield** [comment]
On Linux Mint 17.2 Rafaela:

Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==2.6.5', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 144, in main
    win = MainWindow()
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 23, in __init__
    self.init_logging()
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 49, in init_logging
    log_path = QStandardPaths.writableLocation(QStandardPaths.AppConfigLocation).lower()
AttributeError: type object 'QStandardPaths' has no attribute 'AppConfigLocation'

**Comment by TheFu** [comment]
After recent patching, I'm seeing the same errors that  ChrisMayfield reports above. My initial crash isn't happening anymore.

Are there required environment variables or other required tools?  I'm running the app on a headless server, over remote X/Windows, BTW.

**Comment by ChrisMayfield** [comment]
P.S. All I did was:
```
sudo add-apt-repository ppa:ozmartian/apps
sudo apt-get update
sudo apt-get install vidcutter
```
Perhaps the package is missing a dependency?

**Comment by Magalaan** [comment]
V3 Crashes immediately in 14.04. starting it from the command line tells me this:

Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==2.6.5', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 144, in main
    win = MainWindow()
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 23, in __init__
    self.init_logging()
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 49, in init_logging
    log_path = QStandardPaths.writableLocation(QStandardPaths.AppConfigLocation).lower()
AttributeError: type object 'QStandardPaths' has no attribute 'AppConfigLocation'

**Comment by ozmartian** [comment]
hi guys

plase update to the latest v3 which is now working also for 14.04 versions via the PPA

and there is always the AppImage portable version that should work given any issues with your setup as all lib dependencies are prebundled within..

**Comment by TheFu** [comment]
Just updated. Seeing the GUI now for the first time. Thanks!

**Comment by ozmartian** [comment]
awesome! thanks for the feedback!
